  name: gitartwork from a contribution graph
  on: 
    workflow_dispatch:
    schedule:
      - cron: '39 */8 * * *'

  jobs:
    build:
      name: Make gitartwork SVG
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: jasineri/gitartwork@v1
          with:
              # Use this username's contribution graph  
              user_name: ${{ github.repository_owner }}
              # Text on contribution graph 
              text: JOE HAWK
        - uses: jasineri/simple-push-action@v1
        
        - name: generate github-contribution-grid-artwork.svg
          uses: jasineri/gitartwork@v1
          with:
            github_user_name: ${{ github.repository_owner }}
            svg_out_path: dist/github-contribution-grid-artwork.svg
        
        - name: push github-contribution-grid-artwork.svg to the output branch
          uses: crazy-max/ghaction-github-pages@v3.0.0
          with:
            target_branch: art-output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
